### ISSUE TITLE
Missing Wormhole Data

### ISSUE THREAD

**Issue by mrwulff** [noneuclideanent/arcospheresolution#1]
Any chance to add wormhole data?

**Comment by verso-patrick** [comment]
Would also love to see this!

**Comment by noneuclideanent** [comment]
Wormhole data added. Since wormhole data doesn't have two randomized outputs, I've got it running in a much simpler loop. According to the chart the loop needs a full set of all 8 arcospheres.

You can either use the chart to see which products should run first and load the arcospheres in the chart order, or just keep throwing arcospheres into the gravimetrics facilities until it starts to loop on it's own. If you put the spheres into the right gravimetrics in the right order it'll loop with just the 8 arcospheres. But if you mess up for some reason you can always just add in the ones that seem to be missing and holding things up and it'll run consistently from there.

**Comment by verso-patrick** [comment]
Wow this one is much simpler too - love it! Thank you!
